### ISSUE TITLE
Support for `moveToDrive`

### ISSUE THREAD

**Issue by maasencioh** [zakodium/adonis-datadrive#12]
Researching how to save a file from REST API I found the [`moveToDrive`](https://docs.adonisjs.com/guides/file-uploads#movetodisk) method, which I don't find support for the moment

**Comment by targos** [comment]
What kind of API do you expect? `file.moveToDisk` is a method on a file object, which we don't control.

**Comment by maasencioh** [comment]
sorry, that was in a newer version of Adonis/Core, but I'm confused, will it be using this library if I save it like that?

**Comment by targos** [comment]
Probably not, because datadrive is a layer on top of adonis/drive but doesn't replace it.

**Comment by maasencioh** [comment]
Does it exist for this moment a way to save a file from a request using this library? Currently, I receive a `MultipartFileContract` that I could move to local disk and I guess that after I can re-save it using the library, but it doesn't seem efficient

**Comment by targos** [comment]
I suppose you can create a stream from `file.tmpPath`, write it using `drive.putStream`  and then delete the temporary file? If this works, I think it makes sense to add a method to DataDrive like `drive.moveFromMultipart(file, location, option)` ?

**Comment by maasencioh** [comment]
in that case, `location` should be the disk location where to be saved or the original path?

**Comment by targos** [comment]
It should be `filename`, not location (like we have in `putStream`). The original path can be read from the `file` object.
