### ISSUE TITLE
How to configurate?

### ISSUE THREAD

**Issue by maasencioh** [zakodium/adonis-datadrive#13]
Currently my configuration shows the error 
![image](https://user-images.githubusercontent.com/7273940/134308550-5b9003ea-a5f3-44b4-b2ae-d542e6d0e273.png)

This is because `DiskList` is an empty type in `@ioc:Adonis/Core/Drive`, is any missing step?

**Comment by targos** [comment]
You need to add a `drive.ts` file in your "contracts" directory.

Example:
```ts
declare module '@ioc:Adonis/Core/Drive' {
  interface DisksList {
    local: {
      config: LocalDriverConfig;
    };
    tmp: {
      config: LocalDriverConfig;
    };
  }
}
```

**Comment by maasencioh** [comment]
I did, but it takes the values from node_modules instead

**Comment by targos** [comment]
are the contracts included in the tsconfig?
this is module augmentation, so both should be taken into account (the empty, augmented by your definition)

**Comment by maasencioh** [comment]
Ok, after reviewing again the code it's now `@ioc:Adonis/Core/Drive` instead of `@ioc:Adonis/Addons/Drive`. Thanks!
