### ISSUE TITLE
randomUUID is not a function

### ISSUE THREAD

**Issue by maasencioh** [zakodium/adonis-datadrive#7]
I'm using the local driver, and when I do the `put` method, I get the following error.

![Screen Shot 2021-07-02 at 13 18 03](https://user-images.githubusercontent.com/7273940/124266994-fda40080-db37-11eb-954e-eeb50883484c.png)

**Comment by targos** [comment]
Have you looked into it?

**Comment by maasencioh** [comment]
Yes, it was added in a newer version of node, I added the warning and updated my node version
